---
name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  ci:
    name: Run checks and tests over ${{matrix.otp_vsn}} and ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        otp_vsn: [22, 23, 24]
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp_vsn}}
          rebar3-version: '3.16'
      - run: rebar3 as test xref
      - run: rebar3 as test dialyzer
      - run: rebar3 eunit
      - run: rebar3 ct
      - run: rebar3 cover
